### PR TITLE
Adding @utkarshbhimte to Site Development team

### PR DESCRIPTION
**Pull request by Utkarshbhimte**
Will be happy to help. 👍🏻

### CODE REVIEW

**Review by sagirk — APPROVED** [review]
image 
👆
First of all, congratulations! 🎊 

Welcome to the team, Utkarsh! 🤗 Look forward to building stuff together.

LGTM! 🎉

**Comment by sagirk** [comment]
We're currently in the "UI Design and Content Creation" phase. 

Until site development kicks off, here are a few ["good first issue"](https://github.com/nodejs/website-redesign/labels/good%20first%20issue)s, if you're interested in taking on something in the meanwhile.

**Comment by Utkarshbhimte** [comment]
Cool, I will go through them

**Review by keywordnew — APPROVED** [review]
LGTM!

**Pull request merged**
