### PR TITLE
Create monitoring-node-js-overview.md

### PR DESCRIPTION
**Pull request by bnb**
Creates an overview file for Monitoring docs.

### CODE REVIEW

**Review by codeekage — APPROVED** [review]

**Review by keywordnew — APPROVED** [review]
LGTM

**Review by sagirk — APPROVED** [review]
LGTM! 🎉

**Review by mihalskiy — APPROVED** [review]

**Comment by sagirk** [comment]
@bnb `monitoring-node-js-overview.md` is currently placed in `documentation/0000-template/`. Not sure if that is where we still want it to go (?).

To be consistent with the rest of the content, would it be appropriate to create a new folder `0056-monitoring-node-js-overview`, rename this file to `index.md` and move it there?

Also, the format for metadata at the top has changed in the newer [handbook content](https://raw.githubusercontent.com/nodejs/website-redesign/master/documentation/0001-node-introduction/index.md). So, we may need to update that too.

**Comment by sagirk** [comment]
Metadata format example, as [will](https://github.com/nodejs/nodejs.dev/pull/157) be consumed by [nodejs.dev](https://nodejs.dev):

```md
---
title: An introduction to the npm package manager
description: 'A quick guide to npm, the powerful package manager key to the success of Node.js. In January 2017 over 350000 packages were reported being listed in the npm registry, making it the biggest single language code repository on Earth, and you can be sure there is a package for (almost!) everything.'
authors: flaviocopes
section: Getting Started
---
```

**Comment by keywordnew** [comment]
@sagirk I was about to merge this because it has enough reviews. I'm unclear on whether the later comment was meant to be blocking.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.

**Pull request closed without merging**
