### PR TITLE
Adding @lidoravitan to the development team

### PR DESCRIPTION
**Pull request by lidoravitan**
I'm definitely excited and interested in helping development and redesign.
I've looked at previous meetings, and sure I'll attend the next meetings.

### CODE REVIEW

**Review by sagirk — APPROVED** [review]
LGTM, except for a nit! 🎉

nit: Configure `git` so that it knows who you are:
`git config user.name "<Your Name Here!>"`
`git config user.email "<Your Email Address Here!>"`

Make sure your email address is also added to your [GitHub email list](https://github.com/settings/emails) so that your commits will be properly associated with your account and you will be promoted to `Contributor` once your first commit is landed!

Oh, and welcome to the team, Lidor! 🤗 Excited to have you onboard! 💚

**Comment by sagirk** [comment]
Lidor, we're currently in the "[UI Design and Content Creation](https://github.com/nodejs/website-redesign#ui-design-and-content-creation----current-phase)" phase.

After you've configured your identity successfully in `git` and on GitHub, and until site development kicks off, here are a few ["good first issue"](https://github.com/nodejs/website-redesign/labels/good%20first%20issue)s, if you're interested in taking on something in the meanwhile.

**Comment by lidoravitan** [comment]
@sagirk Amazing! Thanks a lot. sure i'll fix git configuration soon, also take a look on "good first issue". thanks! 💚

**Comment by lirantal** [comment]
Just chiming in to express my support for Lidor.
We worked together for the past ~6 months, and he's very passionate and I believe he will make a great contributor and valuable member on the project and the working group!

**Pull request merged**
