### PR TITLE
Add @imbhargav5 to Site Development team

### PR DESCRIPTION
**Pull request by imbhargav5**
I am very excited to be a part of the development team and play a role in build the next generation Node website!!

### CODE REVIEW

**Review by sagirk — APPROVED** [review]
LGTM! 🎉

Welcome to the team, Bhargav! 🤗 Excited to have you onboard! 💚

**Comment by sagirk** [comment]
Bhargav, we're currently in the "[UI Design and Content Creation](https://github.com/nodejs/website-redesign#ui-design-and-content-creation----current-phase)" phase.

Until site development kicks off, here are a few ["good first issue"](https://github.com/nodejs/website-redesign/labels/good%20first%20issue)s, if you're interested in taking on something in the meanwhile.

**Comment by keywordnew** [comment]
Welcome, @imbhargav5! Please do resolve the conflicts and we'll get this merged.

**Comment by imbhargav5** [comment]
@chowdhurian Just did :)

**Pull request merged**
