### PR TITLE
Adding @zanmarolt to the development team

### PR DESCRIPTION
**Pull request by ZanMarolt**
Added myself to the development team, already attended the meeting. Very excited to lend a hand 💪

### CODE REVIEW

**Review by sagirk — APPROVED** [review]
LGTM! 🎉

Welcome to the team, Zan! 🤗 Excited to have you onboard! 💚

**Comment by sagirk** [comment]
Zan, we're currently in the "[UI Design and Content Creation](https://github.com/nodejs/website-redesign#ui-design-and-content-creation----current-phase)" phase.

Until site development kicks off, here are a few ["good first issue"](https://github.com/nodejs/website-redesign/labels/good%20first%20issue)s, if you're interested in taking on something in the meanwhile.

**Comment by ZanMarolt** [comment]
Thanks! Was thinking on investigating options we have for [[Discussion] - Tech Stack Consideration](https://github.com/nodejs/website-redesign/issues/107)

How does that sound? 😁

**Comment by sagirk** [comment]
@ZanMarolt Please go ahead and do it. 💪 Contributions of all forms are welcome! ❤️ The more the merrier! 🎉

**Pull request merged**
