### PR TITLE
Added @kevjin to the Site Development Team

### PR DESCRIPTION
**Pull request by kevjin**
Over the past couple weeks I have enjoyed being a part of the community that is over at [node/nodejs.dev](https://github.com/nodejs/nodejs.dev), landing [PRs](https://github.com/nodejs/nodejs.dev/pulls/kevjin) and contributing to [issues](https://github.com/nodejs/nodejs.dev/issues/created_by/kevjin) and discussions. I want to contribute more to this initiative and thought I would add myself to the team. Thanks!

### CODE REVIEW

**Comment by LaRuaNa** [comment]
Hey @kevjin would like to have you on board :] and also would be cool if you come to the next meeting https://github.com/nodejs/website-redesign/issues/159 :]

**Comment by kevjin** [comment]
Thanks @LaRuaNa, I'll be there!

**Review by BeniCheni — APPROVED** [review]
Welcome to the team.

**Review by ZYSzys — APPROVED** [review]

**Comment by ahmadawais** [comment]
Would love to have you onboard with us.

**Review by sagirk — APPROVED** [review]
Glad to have you onboard, Kevin! 💚

LGTM! 🎉

**Pull request merged**
